// Wake Up Azure SQL Database
LIB CONNECT TO 'SQL_Centennium-Opleidingen';

SLEEP 30000;

LIB CONNECT TO 'SQL_Centennium-Opleidingen';


DIM_Fuel:
LOAD 
	[CarID]														AS [%Fuel_KEY]
,	SUBFIELD([Meest_voorkomende_brandstof], '+')				AS [Fuel];
SELECT 
	CarID,
	"Meest_voorkomende_brandstof"
FROM "Centennium-Opleidingen".MillenniumCarSales.Cars;


STORE [DIM_Fuel] INTO [lib://DataFiles/Data-Product/MillenniumCars/DIM_Fuel.qvd] (QVD);
DROP TABLE [DIM_Fuel];


DISCONNECT;
